### ISSUE TITLE
Realtime navigation

### ISSUE THREAD

**Issue by joyde3382** [husky/husky_cartographer_navigation#1]
Just looked into your repository and it looks great. I just have a few questions i hope you can answer.

I currently have cartographer up and running using 2d slam with a lidar, and it works very well. Now i just wish to add navigation based on the map generated from cartographer. Are you able to run slam real time together with the navigation? Say putting the robot in an unexplored environment, and letting it explore it all by itself.

Do you have any video/demo of this running live?

Thanks in advance.

**Comment by joekeo** [comment]
Hello,
we implemented move_base alongside with cartographer, it is just a matter of configuring the global cost map based on the map generated by carto, and give it a threshold
```
global_costmap:
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  resolution: 0.05
  static_layer:
    map_topic: /map
    subscribe_to_updates: true
    lethal_cost_threshold: 60
  inflater_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 10

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

```
that is what i aded to base_global_costmap.yaml
